### ISSUE TITLE
Busy indicators don't work on pageload

### ISSUE THREAD

**Issue by sklingler93** [Pier1/rocketbelt#185]
### Summary

Because the busy indicators use MutationObserver to respond to class changes there is no easy way to have the indicators visible as the page loads.

### Steps to reproduce

1. Add a `.is-busyable-page` to a template
2. Add a `.is-busy` inside of the the `.is-busyable-page`
3. Load the page

### What is the current *bug* behavior?

The busy indicator does not appear.

### What is the expected *correct* behavior?

The busy indicator appears.

**Comment by kendrick** [comment]
This is _sort of_ by design; the code today expects `.is-busy` to be transient which IMO lightly contradicts rendering it server-side. That said, this is a super loosely-held opinion and the use case here makes plenty of sense. I'm happy to add a check after page load for `.is-busy` anywhere on the page.

**Comment by sklingler93** [comment]
My issue with that is that there will be a decent chunk of time where no indicator will be visible while JS loads. Our workaround was to drop the `box-loader` markup on the page in it's own `is-busyable-page is-busy` and hide it when everything else renders.
